name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: cargo build --release

      - name: Test ApiLinks Correct
        run: ./target/release/modlinks-sha-verifier api ./test/apilinks/correct.xml

      - name: Test ApiLinks Incorrect
        run: ./target/release/modlinks-sha-verifier api ./test/apilinks/incorrect.xml
        continue-on-error: true

      - name: Test ApiLinks Invalid
        run: ./target/release/modlinks-sha-verifier api ./test/apilinks/invalid.xml
        continue-on-error: true

      - name: Test ModLinks Correct
        run: ./target/release/modlinks-sha-verifier mod ./test/modlinks/correct.xml

      - name: Test ModLinks Incorrect
        run: ./target/release/modlinks-sha-verifier mod ./test/modlinks/incorrect.xml
        continue-on-error: true

      - name: Test ModLinks Invalid
        run: ./target/release/modlinks-sha-verifier mod ./test/modlinks/invalid.xml
        continue-on-error: true
